import { NextResponse } from "next/server"
import { createClient } from "@/lib/supabase/server"
import { notifyUser } from "@/lib/notifications"
import { dispatchTaskEvent } from "@/lib/automations/dispatcher"

interface RouteParams {
  params: Promise<{ id: string }>
}

/** Resolve the byred_users.id for the current auth user and their tenant IDs */
async function getCallerProfile(supabase: Awaited<ReturnType<typeof createClient>>) {
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return null

  const sa = supabase as any
  const { data: byredUserRaw } = await sa
    .from("byred_users")
    .select("id")
    .eq("auth_user_id", user.id)
    .maybeSingle() as { data: { id: string } | null }
  if (!byredUserRaw) return null

  const { data: userTenants } = await sa
    .from("byred_user_tenants")
    .select("tenant_id")
    .eq("user_id", byredUserRaw.id) as { data: Array<{ tenant_id: string }> | null }

  const tenantIds = (userTenants ?? []).map((ut) => ut.tenant_id)
  return { id: byredUserRaw.id, tenantIds }
}

async function writeCompletionReceipt(
  supabase: Awaited<ReturnType<typeof createClient>>,
  args: { tenantId: string; taskId: string; taskTitle: string; actorId: string },
) {
  const sa = supabase as any
  await sa.from("os_agent_receipts").insert({
    tenant_id: args.tenantId,
    related_task_id: args.taskId,
    source_surface: "byred_os/tasks",
    receipt_type: "task_completion",
    agent_family: "codex",
    framework_scope: "byred_os",
    lesson: "Task completion recorded inside the shared OS backend",
    proof_url_or_path: `/os/tasks/${args.taskId}`,
    summary: `Marked ${args.taskTitle} complete`,
    verification_status: "recorded",
    created_by_user_id: args.actorId,
  })
}

export async function GET(_req: Request, { params }: RouteParams) {
  const supabase = await createClient()
  const caller = await getCallerProfile(supabase)
  if (!caller) return NextResponse.json({ error: "Unauthorized" }, { status: 401 })

  const { id } = await params
  const { data, error } = await (supabase as any)
    .from("byred_tasks")
    .select("*")
    .eq("id", id)
    .in("tenant_id", caller.tenantIds)
    .single() as { data: Record<string, unknown> | null; error: { message: string } | null }

  if (error || !data)
    return NextResponse.json({ error: "Not found" }, { status: 404 })
  return NextResponse.json(data)
}

export async function PATCH(request: Request, { params }: RouteParams) {
  const supabase = await createClient()
  const caller = await getCallerProfile(supabase)
  if (!caller) return NextResponse.json({ error: "Unauthorized" }, { status: 401 })

  const { id } = await params

  // Verify this task belongs to one of the caller's tenants
  const { data: existing } = await (supabase as any)
    .from("byred_tasks")
    .select("id, tenant_id, status, title")
    .eq("id", id)
    .maybeSingle() as { data: { id: string; tenant_id: string; status: string; title: string } | null }

  if (!existing) return NextResponse.json({ error: "Not found" }, { status: 404 })
  if (!caller.tenantIds.includes(existing.tenant_id)) {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 })
  }

  const body = (await request.json()) as Partial<{
    title: string
    description: string | null
    status: string
    priority: string
    ai_mode: string
    due_date: string | null
    estimated_minutes: number
    blocker_flag: boolean
    blocker_reason: string | null
    owner_user_id: string | null
    issue_type: string
    story_points: number | null
    start_date: string | null
    labels: string[]
    sprint_id: string | null
  }>

  // Loosely typed — some columns (issue_type, story_points, start_date, labels)
  // are newer than the generated ByredTaskUpdate type.
  const updateRow: Record<string, unknown> = { ...body, updated_at: new Date().toISOString() }
  if (body.status === "complete") {
    updateRow.completed_at = new Date().toISOString()
  }

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const { data, error } = await (supabase as any)
    .from("byred_tasks")
    .update(updateRow)
    .eq("id", id)
    .select()
    .single()

  if (error) return NextResponse.json({ error: error.message }, { status: 500 })
  if (!data) return NextResponse.json({ error: "Not found" }, { status: 404 })

  if (body.status === "complete") {
    void writeCompletionReceipt(supabase, {
      tenantId: existing.tenant_id,
      taskId: id,
      taskTitle: existing.title,
      actorId: caller.id,
    })
  }

  // Collaboration notifications (best-effort, in-app).
  if (body.owner_user_id) {
    void notifyUser({ userId: body.owner_user_id, actorId: caller.id, type: "assignment", body: `You were assigned "${(data as { title?: string }).title ?? "a task"}"`, contextUrl: `/os/tasks/${id}` })
  }
  if (body.blocker_flag === true) {
    void notifyUser({ userId: (data as { owner_user_id?: string | null }).owner_user_id ?? null, actorId: caller.id, type: "blocker", body: `A task you own was flagged blocked: "${(data as { title?: string }).title ?? ""}"`, contextUrl: `/os/tasks/${id}` })
  }

  // Automation event dispatch (best-effort).
  const sa = supabase as any
  if (body.status && body.status !== existing.status) {
    void dispatchTaskEvent(sa, {
      type: "task.status_changed",
      taskId: id,
      tenantId: existing.tenant_id,
      actorId: caller.id,
      payload: { status: body.status, prev_status: existing.status },
    })
  }
  if (body.blocker_flag === true) {
    void dispatchTaskEvent(sa, {
      type: "task.blocker_set",
      taskId: id,
      tenantId: existing.tenant_id,
      actorId: caller.id,
      payload: { blocker_reason: body.blocker_reason ?? null },
    })
  }
  if (body.owner_user_id) {
    void dispatchTaskEvent(sa, {
      type: "task.assigned",
      taskId: id,
      tenantId: existing.tenant_id,
      actorId: caller.id,
      payload: { owner_user_id: body.owner_user_id },
    })
  }

  return NextResponse.json(data)
}

export async function DELETE(_req: Request, { params }: RouteParams) {
  const supabase = await createClient()
  const caller = await getCallerProfile(supabase)
  if (!caller) return NextResponse.json({ error: "Unauthorized" }, { status: 401 })

  const { id } = await params

  // Verify this task belongs to one of the caller's tenants before deleting
  const { data: existing } = await (supabase as any)
    .from("byred_tasks")
    .select("id, tenant_id")
    .eq("id", id)
    .maybeSingle() as { data: { id: string; tenant_id: string } | null }

  if (!existing) return NextResponse.json({ error: "Not found" }, { status: 404 })
  if (!caller.tenantIds.includes(existing.tenant_id)) {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 })
  }

  const { error } = await (supabase as any)
    .from("byred_tasks")
    .update({ status: "cancelled", updated_at: new Date().toISOString() })
    .eq("id", id) as { error: { message: string } | null }

  if (error) return NextResponse.json({ error: error.message }, { status: 500 })
  return NextResponse.json({ success: true })
}
