import { NextResponse } from "next/server"
import { createClient } from "@/lib/supabase/server"

interface RouteParams {
  params: Promise<{ id: string }>
}

/** Resolve the byred_users.id for the current auth user and their tenant IDs */
async function getCallerProfile(supabase: Awaited<ReturnType<typeof createClient>>) {
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return null

  const sa = supabase as any
  const { data: byredUserRaw } = await sa
    .from("byred_users")
    .select("id")
    .eq("auth_user_id", user.id)
    .maybeSingle() as { data: { id: string } | null }
  if (!byredUserRaw) return null

  const { data: userTenants } = await sa
    .from("byred_user_tenants")
    .select("tenant_id")
    .eq("user_id", byredUserRaw.id) as { data: Array<{ tenant_id: string }> | null }

  const tenantIds = (userTenants ?? []).map((ut) => ut.tenant_id)
  return { id: byredUserRaw.id, tenantIds }
}

export async function GET(_req: Request, { params }: RouteParams) {
  const supabase = await createClient()
  const caller = await getCallerProfile(supabase)
  if (!caller) return NextResponse.json({ error: "Unauthorized" }, { status: 401 })

  const { id } = await params
  const { data, error } = await (supabase as any)
    .from("byred_tasks")
    .select("*")
    .eq("id", id)
    .in("tenant_id", caller.tenantIds)
    .single() as { data: Record<string, unknown> | null; error: { message: string } | null }

  if (error || !data)
    return NextResponse.json({ error: "Not found" }, { status: 404 })
  return NextResponse.json(data)
}

export async function PATCH(request: Request, { params }: RouteParams) {
  const supabase = await createClient()
  const caller = await getCallerProfile(supabase)
  if (!caller) return NextResponse.json({ error: "Unauthorized" }, { status: 401 })

  const { id } = await params

  // Verify this task belongs to one of the caller's tenants
  const { data: existing } = await (supabase as any)
    .from("byred_tasks")
    .select("id, tenant_id")
    .eq("id", id)
    .maybeSingle() as { data: { id: string; tenant_id: string } | null }

  if (!existing) return NextResponse.json({ error: "Not found" }, { status: 404 })
  if (!caller.tenantIds.includes(existing.tenant_id)) {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 })
  }

  const body = (await request.json()) as Partial<{
    title: string
    description: string | null
    status: string
    priority: string
    ai_mode: string
    due_date: string | null
    estimated_minutes: number
    blocker_flag: boolean
    blocker_reason: string | null
    owner_user_id: string | null
    issue_type: string
    story_points: number | null
    start_date: string | null
    labels: string[]
    sprint_id: string | null
  }>

  // Loosely typed — some columns (issue_type, story_points, start_date, labels)
  // are newer than the generated ByredTaskUpdate type.
  const updateRow: Record<string, unknown> = { ...body, updated_at: new Date().toISOString() }

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const { data, error } = await (supabase as any)
    .from("byred_tasks")
    .update(updateRow)
    .eq("id", id)
    .select()
    .single()

  if (error) return NextResponse.json({ error: error.message }, { status: 500 })
  if (!data) return NextResponse.json({ error: "Not found" }, { status: 404 })
  return NextResponse.json(data)
}

export async function DELETE(_req: Request, { params }: RouteParams) {
  const supabase = await createClient()
  const caller = await getCallerProfile(supabase)
  if (!caller) return NextResponse.json({ error: "Unauthorized" }, { status: 401 })

  const { id } = await params

  // Verify this task belongs to one of the caller's tenants before deleting
  const { data: existing } = await (supabase as any)
    .from("byred_tasks")
    .select("id, tenant_id")
    .eq("id", id)
    .maybeSingle() as { data: { id: string; tenant_id: string } | null }

  if (!existing) return NextResponse.json({ error: "Not found" }, { status: 404 })
  if (!caller.tenantIds.includes(existing.tenant_id)) {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 })
  }

  const { error } = await (supabase as any).from("byred_tasks").delete().eq("id", id) as { error: { message: string } | null }

  if (error) return NextResponse.json({ error: error.message }, { status: 500 })
  return NextResponse.json({ success: true })
}
